---
name: PR Testing

on:
  pull_request: {}
  push:
    branches:
      - main

# minimal permissions
permissions:
  contents: read

jobs:
  clojure-linting:
    name: Clojure Linting
    runs-on: ubuntu-24.04
    steps:
      - name: setup java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
      - name: checkout repo
        uses: actions/checkout@v6
      - name: Install Clojure tools
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          lein: latest
          clj-kondo: latest
      - name: kondo lint
        run: clj-kondo --lint src test
      - name: eastwood lint
        run: lein eastwood
      - name: output dependencies
        run: lein deps :tree

  run-lein-tests:
    name: PR Testing
    strategy:
      fail-fast: false
      matrix:
        version: ['17', '21']
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.version }}
      - name: Install Clojure tools
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          lein: latest
      - name: clojure tests
        run: lein test
      - name: run acceptance tests
        run: lein uberjar && ext/test/run-all

  tests:
    if: always()
    needs:
      - clojure-linting
      - run-lein-tests
    runs-on: ubuntu-24.04
    name: Test suite
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
